// proto-schema.ts -- prototype for the Effect rewrite (plan step 0.4), run in a project container.
// Usage: node /opt/plan-review/prototypes/proto-schema.ts /path/to/project [output directory]
//
// Determines whether the JSON Schema generated by Effect Schema 4 is accepted by Codex's strict
// structured output and by the Agent SDK. Each of the seven agent schemas of src/schemas.ts is
// defined here as an Effect Schema (self-contained; nothing is imported from src/) and sent in two
// variants:
//   raw    -- Schema.toJsonSchemaDocument(s, { onExcessProperty: "error" }).schema (+ $defs if any)
//   strict -- raw after an inline transform: $ref inlined, every object gets
//             additionalProperties: false and required = all of its property keys.
// Output: one line per agent, schema and variant; files proto-schema-output/<name>.<variant>.json.

import { query } from "@anthropic-ai/claude-agent-sdk";
import { Codex } from "@openai/codex-sdk";
import { Exit, Schema } from "effect";
import { type Classification, classify, counted } from "./classify.ts";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const projectArg = process.argv[2];
if (!projectArg) {
  console.error("usage: node proto-schema.ts /path/to/project [output directory]");
  process.exit(2);
}
const projectDir = path.resolve(projectArg);
// /opt/plan-review is read-only in project containers, so the output goes elsewhere.
const outDir = path.resolve(process.argv[3] ?? path.join(os.tmpdir(), "proto-schema-output"));
fs.mkdirSync(outDir, { recursive: true });

// Transcribed field by field from src/schemas.ts.
const Str = Schema.String;
const Strings = Schema.Array(Schema.String);
const Issue = Schema.Struct({ id: Str, severity: Schema.Literals(["blocking", "major", "minor"]), location: Str, problem: Str, evidence: Str });
const Disposition = Schema.Struct({
  id: Str,
  action: Schema.Literals(["accepted", "partially_accepted", "rejected", "no_change_needed", "clarification_requested"]),
  rationale: Str,
  duplicate_of: Str,
  reverses: Str,
});
const SelfCorrection = Schema.Struct({ id: Str, new_action: Schema.Literals(["accepted", "rejected", "plan_error"]), explanation: Str });
const plannerFields = { dispositions: Schema.Array(Disposition), self_corrections: Schema.Array(SelfCorrection), reviewer_feedback: Str, questions_for_user: Strings };
const QuestionEntry = Schema.Struct({
  id: Str,
  question: Str,
  reason: Str,
  proposed_answers: Schema.Array(Schema.Struct({ label: Str, description: Str })),
  default_answer: Str,
});

const schemas: Record<string, Schema.Top> = {
  review: Schema.Struct({ issues: Schema.Array(Issue) }),
  plannerResponse: Schema.Struct(plannerFields),
  planWrite: Schema.Struct({ questions_for_user: Strings }),
  execReport: Schema.Struct({ status: Schema.Literals(["finished", "needs_input", "blocked"]), summary: Str, question: Str, remaining_work: Str }),
  questionList: Schema.Struct({ questions: Schema.Array(QuestionEntry) }),
  questionListResponse: Schema.Struct({ ...plannerFields, questions: Schema.Array(QuestionEntry) }),
  interviewTurn: Schema.Struct({ message_to_user: Str, answered_ids: Strings, complete: Schema.Boolean, summary: Str }),
};

type Json = Record<string, any>;

function raw(s: Schema.Top): Json {
  const doc = Schema.toJsonSchemaDocument(s, { onExcessProperty: "error" });
  const defs = doc.definitions as Json;
  return Object.keys(defs).length > 0 ? { ...(doc.schema as Json), $defs: defs } : (doc.schema as Json);
}

function strict(json: Json): Json {
  const defs: Json = json.$defs ?? {};
  const walk = (node: unknown): unknown => {
    if (Array.isArray(node)) return node.map(walk);
    if (node === null || typeof node !== "object") return node;
    const n = node as Json;
    if (typeof n.$ref === "string") return walk(defs[n.$ref.replace("#/$defs/", "")]);
    const out: Json = {};
    for (const [k, v] of Object.entries(n)) if (k !== "$defs") out[k] = walk(v);
    if (out.type === "object" && out.properties) {
      out.required = Object.keys(out.properties);
      out.additionalProperties = false;
    }
    return out;
  };
  return walk(json) as Json;
}

// --only=<agent>:<schema>:<variant>, each part optional, for reproducing one case quickly.
const only = (process.argv.find((a) => a.startsWith("--only=")) ?? "").slice("--only=".length).split(":");
const selected = (agent: string, name: string, variant: string): boolean =>
  [agent, name, variant].every((part, i) => !only[i] || only[i] === part);
const TIMEOUT_MS = 120_000;
const say = (line: string): void => void process.stdout.write(line + "\n");

const prompt = (name: string): string =>
  `This is a test of structured output. Do not read or change any file. Return a minimal valid instance of the required output schema (${name}); use empty arrays where allowed.`;
const decodes = (s: Schema.Top, value: unknown): boolean => Exit.isSuccess(Schema.decodeUnknownExit(s as any, { onExcessProperty: "error" })(value));
const decodeText = (decoded: boolean): string => (decoded ? "decodes" : "DOES NOT DECODE");
const oneLine = (e: unknown): string => (e instanceof Error ? e.message : String(e)).replace(/\s+/g, " ").slice(0, 300);
const timedOut = (e: unknown): boolean => e instanceof Error && (e.name === "TimeoutError" || /abort|timeout/i.test(e.message));
// A call counts as accepted only when the transport accepted the schema and the reply decoded (finding 32; prototypes/classify.ts).
const counts = { accepted: 0, other: 0 };
const report = (line: string, started: number, classification: Classification): void => {
  counts[counted(classification) ? "accepted" : "other"]++;
  say(`${line} (${Math.round((Date.now() - started) / 1000)} s)`);
};

const codex = new Codex();
for (const variant of ["raw", "strict"] as const) {
  const thread = codex.startThread({ workingDirectory: projectDir, sandboxMode: "danger-full-access", approvalPolicy: "never" });
  for (const [name, s] of Object.entries(schemas)) {
    const json = variant === "raw" ? raw(s) : strict(raw(s));
    fs.writeFileSync(path.join(outDir, `${name}.${variant}.json`), JSON.stringify(json, null, 2) + "\n");

    if (selected("codex", name, variant)) {
      say(`-> codex  ${name} ${variant} ...`);
      const started = Date.now();
      try {
        const turn = await thread.run(prompt(name), { outputSchema: json, signal: AbortSignal.timeout(TIMEOUT_MS) });
        const decoded = decodes(s, JSON.parse(turn.finalResponse));
        report(`codex  ${name} ${variant}: accepted, ${decodeText(decoded)}`, started, classify("accepted", decoded));
      } catch (e) {
        const timeout = timedOut(e);
        report(`codex  ${name} ${variant}: ${timeout ? `TIMEOUT after ${TIMEOUT_MS / 1000} s` : `REJECTED: ${oneLine(e)}`}`, started, classify(timeout ? "timeout" : "rejected", false));
      }
    }

    if (selected("claude", name, variant)) {
      say(`-> claude ${name} ${variant} ...`);
      const started = Date.now();
      const abort = new AbortController();
      const timer = setTimeout(() => abort.abort(new Error("timeout")), TIMEOUT_MS);
      try {
        let result = "no result message";
        let classification: Classification = "rejected";
        for await (const m of query({
          prompt: prompt(name),
          options: { cwd: projectDir, permissionMode: "default", maxTurns: 3, outputFormat: { type: "json_schema", schema: json }, abortController: abort, canUseTool: async () => ({ behavior: "deny", message: "not permitted in this test" }) },
        })) {
          if (m.type === "result") {
            const decoded = m.subtype === "success" && decodes(s, m.structured_output);
            classification = classify(m.subtype === "success" ? "accepted" : "rejected", decoded);
            result = m.subtype === "success" ? `accepted, ${decodeText(decoded)}` : `REJECTED: ${m.subtype}`;
          }
        }
        report(`claude ${name} ${variant}: ${abort.signal.aborted ? `TIMEOUT after ${TIMEOUT_MS / 1000} s` : result}`, started, abort.signal.aborted ? "timeout" : classification);
      } catch (e) {
        report(`claude ${name} ${variant}: ${abort.signal.aborted ? `TIMEOUT after ${TIMEOUT_MS / 1000} s` : `REJECTED: ${oneLine(e)}`}`, started, abort.signal.aborted ? "timeout" : "rejected");
      } finally {
        clearTimeout(timer);
      }
    }
  }
}
say(`\n${counts.accepted} accepted, ${counts.other} not accepted. Schemas written to ${outDir}`);
